WebMarke_App/Controllers/ValueController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMarke_App.Data;
using WebMarke_App.Models;
using WebMarke_App.Models.ViewModel;

namespace WebMarke_App.Controllers
{
    public class ValueController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ValueController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<FildeValue> ValueList = _db.Values;
            return View(ValueList);
        }

        public IActionResult Upsert(int? id)
        {
            ValueShowcase valueVM = new()
            {
                Value = new(),
                ProductListValue = _db.Products.Select(i => new SelectListItem
                {
                    Text = i.Title,
                    Value = i.Id.ToString(),
                }).ToList(),
                FieldList = _db.Fields.Select(i => new SelectListItem
                {
                    Text = i.Filde,
                    Value = i.Id.ToString(),
                }).ToList(),
            };
            if (id == null || id == 0)
            {
                return View(valueVM);
            }
            else
            {
                valueVM.Value = _db.Values.FirstOrDefault(u => u.Id == id);
                return View(valueVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(ValueShowcase obj)
        {
            if (obj.Value.Id == 0)
            {
                _db.Values.Add(obj.Value);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                _db.Values.Update(obj.Value);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
        }
    }
}

WebMarke_App/Views/Value/Index.cshtml
@model IEnumerable<FildeValue>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-black">لیست مقدار ها</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Value" asp-action="upsert" class="btn btn-outline-dark">ایجاد مقدار جدید</a>
        </div>
    </div>
    <br />
    <table class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>
                    نام مقدار
                </th>
                <th>
                    محصول
                </th>
                <th>
                    فیلد
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Value
                    </td>
                    <td width="50%">
                        @obj.ProductId
                    </td>
                    <td width="50%">
                        @obj.FildeId
                    </td>
                    <td>
                        <div class="m-75 btn-group" role="group">
                            <a asp-controller="Value" asp-action="upsert" asp-route-id="@obj.Id">
                                ویرایش
                            </a>
                        </div>
                    </td>
                    <td>
                        <div class="m-75 btn-group" role="group">
                            <a asp-controller="value" asp-action="delete" asp-route-id="@obj.Id">
                                حذف
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

WebMarke_App/Views/Value/Upsert.cshtml
@using WebMarke_App.Models.ViewModel
@model ValueShowcase
@{
    ViewData["Title"] = "Upsert";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    <input asp-for="Value.Id" type="hidden" />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>@(Model.Value.Id != 0 ? "ویرایش" : "ایجاد") مقدار</h2>
            <hr />
            <div class="mb-3">
                <label asp-for="Value.Value"></label>
                <input asp-for="Value.Value" class="form-control" />
                <span asp-validation-for="Value.Value" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Value.ProductId"></label>
                <select asp-for="Value.ProductId" asp-items="@Model.ProductListValue" class="form-select">
                    <option disabled selected>---انتخاب محصول---</option>
                </select>
                <span asp-validation-for="Value.ProductId" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="Value.FildeId"></label>
                <select asp-for="Value.FildeId" asp-items="@Model.FieldList" class="form-select">
                    <option disabled selected>---انتخاب فیلد---</option>
                </select>
                <span asp-validation-for="Value.FildeId" class="text-danger"></span>
            </div>
            <div class="col-12">
                @if (Model.Value.Id != 0)
                {
                    <button type="submit" class="btn btn-outline-dark m-auto" style="width:150px">ویرایش فیلد</button>
                }
                else
                {
                    <button type="submit" class="btn btn-outline-dark m-auto" style="width:150px">ایجاد فیلد</button>
                }
                <a asp-controller="value" asp-action="Index" class="btn btn-outline-dark m-auto" style="width:150px">بازگشت به لیست</a>
            </div>
        </div>
    </div>
</form>