WebMarke_App/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMarke_App.Data;
using WebMarke_App.Models;
using WebMarke_App.Models.ViewModel;

namespace WebMarke_App.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Category> CategoryList = _db.Categories;
            return View(CategoryList);
        }


        public IActionResult Upsert(int? id)
        {
            CategoryShowcase categoryVM = new()
            {
                Category = new(),
                CategoryList = _db.Categories.Where(x => x.ParentId == null).Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                }).ToList(),
            };
            if (id == null || id == 0)
            {
                return View(categoryVM);
            }
            else
            {
                categoryVM.Category = _db.Categories.FirstOrDefault(u => u.Id == id);
                return View(categoryVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(CategoryShowcase obj)
        {
            if (obj.Category.Id == 0)
            {
                _db.Categories.Add(obj.Category);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                _db.Categories.Update(obj.Category);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDbFirst = _db.Categories.FirstOrDefault(i => i.Id == id);
            if (categoryFromDbFirst == null)
            {
                return NotFound();
            }
            return View(categoryFromDbFirst);
        }
        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Categories.FirstOrDefault(i => i.Id == id);
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

WebMarke_App/Controllers/FieldController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebMarke_App.Data;
using WebMarke_App.Models;
using WebMarke_App.Models.ViewModel;

namespace WebMarke_App.Controllers
{
    public class FieldController : Controller
    {
        private readonly ApplicationDbContext _db;

        public FieldController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Field> FieldList = _db.Fields;
            return View(FieldList);
        }

        public IActionResult Upsert(int? id)
        {
            FieldShowcase fieldVM = new()
            {
                Field = new(),
                CategoryList = _db.Categories.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                }).ToList(),
            };
            if (id == null || id == 0)
            {
                return View(fieldVM);
            }
            else
            {
                fieldVM.Field = _db.Fields.FirstOrDefault(u => u.Id == id);
                return View(fieldVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(FieldShowcase obj)
        {
            if (obj.Field.Id == 0)
            {
                _db.Fields.Add(obj.Field);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
            else
            {
                _db.Fields.Update(obj.Field);
                _db.SaveChanges();
                return RedirectToAction("index");
            }
        }
    }
}

WebMarke_App/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using WebMarke_App.Data;
using WebMarke_App.Models;
using WebMarke_App.Models.ViewModel;

namespace WebMarke_App.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _WebHostEnviroment;

        public ProductsController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _WebHostEnviroment = webHostEnvironment;
        }


        public IActionResult Index(double min, double max, int? id, string? searche, int? categoryId, int?[] fieldId, string? value)
        {
            //var products = from product in _db.Products select product;
            //if (id.HasValue)
            //{
            //    var idd = id.Value;
            //    products = products.Where(x => x.Id == idd);
            //}

            //if (!String.IsNullOrEmpty(searche))
            //{
            //    products = products.Where(p => p.Title.Contains(searche));
            //}

            //if (max == 0)
            //{
            //    max = _db.Products.Max(product => product.Price);
            //}
            //var filterPrice = from product in _db.Products select product;
            //filterPrice = _db.Products.Where(f => f.Price >= min && f.Price <= max);

            //if (categoryId == null)
            //{
            //    ProductShowcase products = new()
            //    {
            //        Categoryy = _db.Categories.ToList(),
            //        ProductList = _db.Products.ToList()
            //    };
            //    return View(products);
            //}
            //ProductShowcase filter = new()
            //{
            //    Categoryy = _db.Categories.ToList(),
            //    ProductList = _db.Products.Where(i => i.Id == categoryId).ToList()
            //};
            //return View(filter);

            //Console.WriteLine(fieldId);
            if (value == null)
            {
                ProductShowcase products = new()
                {
                    Categoryy = _db.Categories.ToList(),
                    ProductList = _db.Products.ToList(),
                    FieldList = _db.Fields.ToList(),
                };
                return View(products);
            }
            ProductShowcase filter = new()
            {
                Categoryy = _db.Categories.ToList(),
                ProductList = _db.Products
                .Where(i => i.FildeValues.Any(x => x.Value.Contains(value) && fieldId.Contains(x.FildeId.Value))).ToList(),
                FieldList = _db.Fields.ToList(),
            };
            return View(filter);
        }


        public async Task<ActionResult> Upsert(int? id)
        {
            ProductShowcase product = new()
            {
                Product = new(),
                CategoryList = await _db.Categories.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString(),
                }).ToListAsync(),
            };
            if (id == null || id == 0)
            {
                return View(product);
            }
            else
            {
                product.Product = await _db.Products.FirstOrDefaultAsync(u => u.Id == id);
                return View(product);
            }
        }

        [HttpPost]
        public IActionResult Upsert(ProductShowcase obj)
        {
            string wwwrootPath = _WebHostEnviroment.WebRootPath;
            if (ModelState.IsValid)
            {
                if (obj.Product.File != null)
                {
                    string FileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwrootPath, @"img");
                    var extention = Path.GetExtension(obj.Product.File.FileName);

                    if (obj.Product.Img != null)
                    {
                        var oldImgPath = Path.Combine(wwwrootPath, obj.Product.Img.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImgPath))
                        {
                            System.IO.File.Delete(oldImgPath);
                        }
                    }

                    using (var FileStream =
                           new FileStream(Path.Combine(uploads, FileName + extention), FileMode.Create))
                    {
                        obj.Product.File.CopyTo(FileStream);
                    }

                    obj.Product.Img = @"img/" + FileName + extention;
                }

                if (obj.Product.Id == 0)
                {
                    _db.Products.Add(obj.Product);
                    _db.SaveChanges();
                    return RedirectToAction("index");
                }
                else
                {
                    _db.Products.Update(obj.Product);
                    _db.SaveChanges();
                    return RedirectToAction("index");
                }
            }

            return View(obj);
        }



        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var ProductDbFirst = _db.Products.FirstOrDefault(i => i.Id == id);
            if (ProductDbFirst == null)
            {
                return NotFound();
            }

            return View(ProductDbFirst);
        }

        [HttpPost]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Products.FirstOrDefault(i => i.Id == id);
            _db.Products.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

WebMarke_App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMarke_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebMarke_App.styles.css" asp-append-version="true" />
</head>
<body dir="rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebMarke_App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">محصولات</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">دسته بندی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Field" asp-action="Index">فیلد</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="value" asp-action="Index">مقدار</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebMarke_App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>